[package]
name = "blue-pill-quickstart"
version = "0.1.0"
authors = ["Colm Cavanagh"]
edition = "2018"

[dependencies]
stm32f1xx-hal = { version = "0.4", features = ["rt", "stm32f103" ] }
cortex-m = "0.6"
cortex-m-rt = { version = "0.6.6", features = ["device"] }
panic-semihosting = "0.5"
void = { version = "1", default_features = false }
cortex-m-semihosting = "0.3.4"
